name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout del código
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    # 3. Instalar dependencias del backend
    - name: Install dependencies (Backend)
      run: |
        cd backend
        npm install

    # 4. Correr pruebas del backend
    - name: Run tests (Backend)
      run: |
        cd backend
        npm test

    # 5. Construir la imagen Docker
    - name: Build Docker image
      run: |
        docker build -t hanler11/proyecto .

    # 6. Iniciar sesión en Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. Subir imagen Docker a Docker Hub
    - name: Push Docker image
      run: |
        docker push hanler11/proyecto

    # 8. Desplegar (opcional, ajusta según tu entorno)
    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
          docker pull hanler11/proyecto
          docker run -d -p 80:80 hanler11/proyecto
        EOF
